tester:
  cwd: /home/papastrat/PycharmProjects/PyramidTransformer # working directory
  logger: SLR_challenge # logger name
  seed: 1234 # randomness seed
  cuda: True # use nvidia gpu
  gpu: 0 # id of gpu
  save: True # save checkpoint
  load: True # load pretrained checkpoint
  pretrained_cpkt: /home/iliask/PycharmProjects/PyramidTransformer/checkpoints/model_Pyramid_Transformer/dataset_AUTSL/date_03_03_2021_10.24.19/best_model_epoch_7.pth
  log_interval: 1000 # print statistics every log_interval
  model:
    name: IR_CSN_152 # model name
  dataloader:
    train:
      batch_size: 4 # batch size
      shuffle: True # shuffle samples after every epoch
      num_workers: 4 # number of thread for dataloader
    val:
      batch_size: 1
      shuffle: False
      num_workers: 2
    test:
      batch_size: 1
      shuffle: False
      num_workers: 2
  dataset:
    input_data: data/ # data directory
    name: AUTSL # dataset name
    modality: depth # type of modality
    classes: 226 # number of classes
    normalize: True # mean, std normalization
    padding : True # pad videos
    dim: [224,224] # frame dimension
    train:
      seq_length: 64 # number of frames for each video
      augmentation: True # do augmentation to video
    val:
      seq_length: 64
      augmentation: False
    test:
      seq_length: 64
      augmentation: False